number1= input("Enter first number:")
number2= input("Enter second number:")
number3= input("Enter number 3:")
number4= input("Enter number 4:")
number5= input("Enter number 5:")
number6= input("Enter number 6:")
number7= input("Enter number 7:")
number8= input("Enter number 8:")
set_of_uniq_number={int(number1),int(number2),int(number3),int(number4),int(number5),int(number6),int(number7),int(number8)}
print(set_of_uniq_number)
